// route
export const CHANGE_ROUTE = 'CHANGE_ROUTE';

// environment
export const WINDOW_RESIZE = 'WINDOW_RESIZE';
export const EXPLOIT_MOVE_LEFT = 'EXPLOIT_MOVE_LEFT';

// exploit
export const SWITCH_LEFT_MENU = 'SWITCH_LEFT_MENU' ;
export const EXPAND_LEFT_MENU = 'EXPAND_LEFT_MENU' ;
export const SWITCH_BOARD_MAP = 'SWITCH_BOARD_MAP';
export const FLOW_TRANSFORMX = 'FLOW_TRANSFORMX';
export const SWITCH_ACTIVE_BOARDID = 'SWITCH_ACTIVE_BOARDID';
export const UPDATE_BOARD_MAP = 'UPDATE_BOARD_MAP';

// dataSource
export const CHANGE_OPENKEYS_DATA = 'CHANGE_OPENKEYS_DATA';
export const CHANGE_ISSCROLL_DATA = 'CHANGE_ISSCROLL_DATA';
